repos:
  # SECURITY
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.4"
    hooks:
      - id: bandit
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.0
    hooks:
      - id: python-safety-dependencies-check
        args: [--ignore=1 ]
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets

  # FORMATTING & MISC
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: check-case-conflict
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: fix-byte-order-marker
      - id: check-merge-conflict
      - id: detect-private-key
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
  - repo: https://github.com/codespell-project/codespell
    rev: v2.0.0
    hooks:
      - id: codespell
        entry: bash -c 'codespell "$@" || true' -- # Don't block, just alert
        verbose: true
        exclude: docs/*
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.2.1"
    hooks:
      - id: prettier
        files: .*\.(ya?ml|json|md)$
        exclude: (?x)^(
          .pre-commit-config.yaml|
          mkdocs.yml|
          )$
  # PYTHON FORMATTING
  - repo: https://github.com/ambv/black
    rev: "22.3.0"
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: "5.0.4"
    hooks:
      - id: flake8
        args: ["--max-line-length=138", --ignore=F401]

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
      - id: reorder-python-imports
        args: [--py3-plus]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.2.2
    hooks:
      - id: pyupgrade
        args: [--py36-plus]
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.1.0
    hooks:
      - id: add-trailing-comma
        args: [--py36-plus]
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.0.0
  #   hooks:
  #     - id: mypy
  #       entry: bash -c 'mypy "$@" || true' -- # Don't block, just alert
  #       verbose: true
  #       exclude: tests/unit/*

  # - repo: https://github.com/pycqa/isort
  #   rev: 5.8.0
  #   hooks:
  #     - id: isort
  #       name: isort (python)
  # CFN CHECKS & LINTING
  - repo: https://github.com/aws-cloudformation/cfn-python-lint
    rev: v0.72.0 # The version of cfn-lint to use
    hooks:
      - id: cfn-python-lint
        files: .*\.(ya?ml)$
        exclude: (?x)^(
          .pre-commit-config.yaml|
          .gitlab-ci.yml|
          mkdocs.yml|
          config.yaml|
          )$
  - repo: https://github.com/stelligent/cfn_nag
    rev: "v0.8.10"
    hooks:
      - id: cfn-nag
        files: .*\.(ya?ml|json)$
        exclude: (?x)^(
          .pre-commit-config.yaml|
          mkdocs.yml|
          cdk.json|
          .gitlab-ci.yml|
          config.yaml|
          )$